from __future__ import annotations

from pathlib import Path
from typing import Any, Mapping, Protocol, Sequence, runtime_checkable

JsonObject = dict[str, Any]


@runtime_checkable
class MicroSystem(Protocol):
    """Test-only port required by the materialized Micro suite."""

    def intake(self, request: Mapping[str, Any]) -> JsonObject: ...

    def get_source(self, source_id: str) -> JsonObject: ...

    def canonical_snapshot(self) -> JsonObject: ...

    def propose_contact_changeset(self, source_id: str) -> JsonObject: ...

    def preview_changeset(self, changeset_id: str) -> JsonObject: ...

    def approve_changeset(self, changeset_id: str, actor: str) -> JsonObject: ...

    def publish_changeset(
        self, changeset_id: str, idempotency_key: str
    ) -> JsonObject: ...

    def get_changeset(self, changeset_id: str) -> JsonObject: ...

    def get_publish_attempts(self, changeset_id: str) -> Sequence[JsonObject]: ...

    def get_receipt(self, receipt_id: str) -> JsonObject: ...

    def read_core_view(self, view_name: str, session_id: str) -> JsonObject: ...

    def query_relationship_contact(self, at: str) -> JsonObject: ...

    def revert_changeset(
        self, changeset_id: str, idempotency_key: str
    ) -> JsonObject: ...

    def list_audit_events(self, changeset_id: str) -> Sequence[JsonObject]: ...

    def inject_failure(self, failure_point: str) -> None: ...

    def reconcile_views(self) -> JsonObject: ...

    def advance_revision_for_test(self) -> JsonObject: ...

    def propose_retry(self, changeset_id: str) -> JsonObject: ...


class AdapterModule(Protocol):
    def create_system(
        self, fixture: Mapping[str, Any], data_root: Path
    ) -> MicroSystem: ...
